apiVersion:       extensions/v1beta1
kind:             Deployment
metadata:
  name:           test-etcd
spec:
  replicas:       1
  template:
    metadata:
      labels:
        app:      test-etcd
    spec:
      containers:
      - name:     etcd2
        image:    quay.io/coreos/etcd:v2.3.8
        ports:
        - containerPort: 2379
        env:
        - name:   ADVERTISE_CLIENT_URLS
          value:  http://0.0.0.0:2379
        - name:   LISTEN_CLIENT_URLS
          value:  http://0.0.0.0:2379
---
apiVersion:       v1
kind:             Service
metadata:
  name:           etcd-svc
spec:
  ports:
    - port:       2379
      targetPort: 2379
  selector:
    app:          test-etcd
