apiVersion:              batch/v2alpha1
kind:                    CronJob
metadata:
  name:                  hourly-backup
spec:
  schedule:              "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:        counter
            image:       centos:7
            command:
              - "bin/bash"
              - "-c"
              - "curl reshifter:8080/v1/backup"
              - "-d '{ \"endpoint\": \"http://172.17.0.2:2379\", \"remote\" : \"play.minio.io:9000\", \"bucket\" : \"reshifter-2017\" }'"
          restartPolicy: OnFailure
