sudo:             required

notifications:
  email:
    on_success:   always
    on_failure:   never

service:          docker

language:         go

go:
  - 1.8


before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

install:
  - make gbuild

before_script:
  - pip install --upgrade httpie
  - apt-get install jq
  - cd testbed

script:
  - ./e2e-etcd2.sh
  - ./e2e-etcd3.sh
