sudo:             required

notifications:
  email:
    on_success:   always
    on_failure:   never

services:         docker

language:         go

go:
  - 1.8


before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

install:
  - make ginstall

before_script:
  - sudo pip install --upgrade httpie
  - sudo apt-get install jq
  - cd testbed

script:
  - ./e2e-etcd2.sh
  - ./e2e-etcd3.sh
