sudo:           required

services:
  - docker

language:       go

go:
  - '1.8'

env:
  global:
    - secure:   "WiAhUlBppmJ6HEwhr/twFaxvSylv8SJGTDfrYfZMT0nmpGWP6CQdenyUOsv1MJbWdUM5eS6V0Nst0jc4lVNXwrMJpw0ydtAIETP9mZcnMPW1IG/XcAbugofDshZd28+/pbjbRP4Qh3gITI2EDxLOAnh6FiSrTIjNalPzrHdDRVL2t0K99ZsZGbz5BlRIzfDsF39jZBxGnWJGIlfPh/FWsBKmI3z5ripWCEdwE5UJUeE628EL1tvnIGfXjNNWLd+DKGsdTcVsemge6UTslhmKdoVQjWuOkNiJTo77fod+Pkx1F9aU7rjiNgifwizVYB1Z4CxmvwSRDEIkNcAju5vX+2c6NI1cVK+SRiXoLalNBDNd3KEOws3VNNpLjIcP7YkbKY5dXf8cFFCAV3brPWm1bK/DnxyvR494Psr7rUZmV6tMBLaKQzPUw4pF6WGS7tt9s3ApvR2ZZ8b57gsPiRl+tVIvhjXO3gyf7vmBl8YgHgyjnG4h7+GGHlcbNhMNH6vjJHUDJmGXOyvGjKH280eLCgsI1BqaZYZe6H/0NRd4iFPU6/mUTCRbgmwHQHIKLwcKduCJVIElji9ZWUJq+c3ojBOCf8UQpMN7i226hxqK6tYEe5q+Jm0svduJCyxGAvVw9+afSMw6UMp/jb/CiN3KrAVQI8UIuk/M6ZJ+FxStLYQ="
    - secure:   "gkW39noHg6x0cGPnRfbbmiRhCXxSNON3yXvODh9DaOp106F96snLZ2n+Icnh4C9sDHcTUaByLS0hUFIGr/tBhGztVGxnKbKmaPKVYyY0CtwoDtACMBpXAMD5SlKwBUC++rB+JpVphMYEZyN08KG6d+Re85Wz5BsJn99AcLNuY131oXhghpEPePTGMg1ST6xly/adrdmjl+soaLDdo8fHCjAawpI/52LBiq4nGNy9bMBQ4szzVE8Z8BmzKiPn9KDMGU/Du1L+UbKVKo4lPMXWy8k4dCeQuu+pILWO4Q45rEL+MIhXl61/kZ1vtlqL0PN7oceKDUFAhT6GBGXzRjd90/81xFLEQcuAR2NKKjzgg0/rCWu5t2MvC0r8BuqCAiyopjLCgpk4O+ijvIv37dSswOUWnnRLici5wowrgyVMMAImU9gW5kYrL6g0XVnYcSgQr706bngbQHEftbx6Z7DjuRdjNxq7oT8C7VAdz5dxItLXc0PjgJP6I3KrveyM8m4zbUoZbvY6TxHP/M9dMaHi/LNywtrQskPNFwueq/PaK1+FnbhU1rcfnBxAF9Da2TWa230MHmo21PHbKWS6JjCIZG4Ogi3sz8EuMuVUtmqFsEErpH3TBfhzE5U1JRZXwll3qeoHQYE4zWM4+sUakbm+/Yxy4TLbTIB+gjMIhmuHJ6s="
    - secure:   "HRsmZOHRtQPBWxxDnZk1OKpIKNU8TXt05v2uzmLby/tW0LvDtdZuCIw1+FT8/fAxAQKRNLbFbA3B3SY0AQgvDor/lxHXjV9H/915H8983onI5T+OJIMgXg4vENjqS5DhmNKP0CDBjz02/yXk9ykiUZEyr3FgQCv/ZCs2h7cC1yGLgj2VQz3UB0we7v23xv7Cd3hQIHw2TEr09b4rBtyz6zxNLFCwB0lgLD6N/IKuahD+IoUfVLk8x8SM79wIn/jKlbr9MuZxUDaqFKlJCamJOQTcHzOrxbuq96Ig+haPNWcIsKnEa6WK1L3bGJPXYSjcuvjgmn3tW8mT5X3YVqlmQGkWcISQdP1tWIcI4qV1/GrV+TL1tT33Tnzt7S68WH+bZpXbZhwEiFJKR3zhZdZ9+7qSIj9XFByMebqur8Js3nO0lXzpX92pNUJmsWY/ivvlAKAnynMUUSOSRQzTSYr638fkxhl9XwICu9YmUWcHzQSo8op57M8tScalphavxzCTdslVQVXvRnWG+ZUBCkjhqvwF2udR1oZ0MMNy2JsoDI7GE1tVLJCsUEex0eyXIDyo/OnFsgu03LB2TzuxIO9YhQXUtc/sPzOqY6OmcTvd1VSDd8+gnlfHDWti2GPam8xO4OOmhZ/JNB1n6EDddITlhLl4GYS0rwNfKyGCx6Bmcm8="

after_success:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=mhausenblas/reshifter
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
