[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "2.1.0"
